-- GENERATED by tools/sync-data.mjs. Do not edit by hand.
-- Source: public/index.html via public/data/*.json.
--
-- Apply from the site/ directory:
--   npx wrangler d1 execute zecat --remote --file=./db/schema.sql
--   npx wrangler d1 execute zecat --remote --file=./db/seed.sql
--
-- Post bodies archive published X posts. Preserve their exact text,
-- including lowercase, to avoid misquoting the originals.
--
-- No password is stored here. Set the admin verifier separately.

INSERT OR IGNORE INTO memes (id, slug, title, alt, tag, credit, featured, sort, stored) VALUES
  (1, 'wanted-on-zcash', 'Wanted on Zcash', 'A pinned wanted poster reading wanted on Zcash, with a mugshot of the tabby cat in dark sunglasses holding a board that says ZECAT.', 'poster', NULL, 1, 10, 0),
  (2, 'cant-dox-the-cat', 'You cannot dox the cat', 'The tabby cat in dark sunglasses beside lettering about being impossible to identify.', 'poster', NULL, 1, 20, 0),
  (3, 'zero-identity', 'Zero identity', 'The tabby cat in dark sunglasses on a near black ground with gold lettering.', 'poster', NULL, 1, 30, 0),
  (4, 'born-at-SHLD-FUN', 'Born at shld.fun', 'The tabby cat in dark sunglasses with gold lettering naming shld.fun as his birthplace.', 'poster', NULL, 0, 40, 0),
  (5, 'selectively-active', 'Selectively active', 'The tabby cat in dark sunglasses, lying down, with gold lettering.', 'poster', NULL, 0, 50, 0),
  (6, 'the-ZECATfather', 'The Zecatfather', 'The tabby cat in dark sunglasses sitting behind a desk in a dim room, posed like a crime boss.', 'scene', NULL, 0, 60, 0),
  (7, 'newspaper', 'The morning paper', 'The tabby cat in dark sunglasses reading a newspaper.', 'scene', NULL, 0, 70, 0),
  (8, 'programmers-WAITING', 'The programmers wait', 'A wide dim room of screens with the tabby cat in dark sunglasses among them.', 'scene', NULL, 0, 80, 0),
  (9, 'alone-at-the-bar', 'Alone at the bar', 'The tabby cat in dark sunglasses sitting alone at a bar counter under a warm light.', 'scene', NULL, 0, 90, 0),
  (10, 'waiting-for-the-grill', 'Waiting for the grill', 'The tabby cat in dark sunglasses waiting beside a grill.', 'scene', NULL, 0, 100, 0),
  (11, 'floor-after-one-drink', 'One drink in', 'The tabby cat in dark sunglasses lying on the floor beside a glass.', 'scene', NULL, 0, 110, 0),
  (12, 'meditation', 'Meditation', 'The tabby cat in dark sunglasses sitting still in a calm pose.', 'scene', NULL, 0, 120, 0),
  (13, 'motorcycle', 'Night ride', 'The tabby cat in dark sunglasses on a motorcycle at night.', 'scene', NULL, 0, 130, 0),
  (14, 'mural-and-cat', 'The mural', 'The tabby cat in dark sunglasses in front of a tall painted wall.', 'scene', NULL, 0, 140, 0),
  (15, 'flying', 'Flying', 'The tabby cat in dark sunglasses up in the air over a dark ground.', 'scene', NULL, 0, 150, 0),
  (16, 'rolling-pin', 'Rolling pin', 'The cat in a floral shirt at a kitchen counter, both paws on a rolling pin beside a pile of flour and two eggs.', 'scene', NULL, 0, 160, 0),
  (17, 'in-the-pot', 'In the pot', 'The cat sitting upright inside a steel saucepan on a gas hob, in front of patterned yellow tiles.', 'scene', NULL, 0, 170, 0),
  (18, 'behind-the-wheel', 'Behind the wheel', 'The cat gripping a car steering wheel with its mouth wide open, trees going past the window.', 'scene', NULL, 0, 180, 0),
  (19, 'spotter', 'Spotter', 'Two cats standing in a gym, the big one pressing a loaded barbell overhead and the small one holding a much lighter bar.', 'scene', NULL, 0, 190, 0),
  (20, 'closing-time', 'Closing time', 'The cat draped face down across a bar stool in a pub, with bottles and beer taps behind.', 'scene', NULL, 0, 200, 0),
  (21, 'bench-press', 'Bench press', 'The cat lying on its back on a dark gym floor, pressing a bending barbell loaded with plates.', 'scene', NULL, 0, 210, 0),
  (22, 'deckchair', 'Deckchair', 'The cat in red sunglasses sitting in a red and white striped deckchair, sea and sky behind.', 'scene', NULL, 0, 220, 0),
  (23, 'nap', 'Nap', 'The cat resting against a sleeping dog on a soft grey blanket.', 'scene', NULL, 0, 230, 0),
  (24, 'the-suit', 'The suit', 'A blurry photo of the cat in a black suit and white shirt, one paw gripping the lapel.', 'scene', NULL, 0, 240, 0),
  (25, 'on-call', 'On call', 'The cat in a blue surgical cap with a stethoscope round its neck, standing in a clinic.', 'scene', NULL, 0, 250, 0),
  (26, 'life-vest', 'Life vest', 'The cat in a pink floral life vest, front paws on the rail of a boat, looking out over a lake.', 'scene', NULL, 0, 260, 0),
  (27, 'six-monitors', 'Six monitors', 'The cat at an office desk facing six monitors full of spreadsheets and charts.', 'scene', NULL, 0, 270, 0),
  (28, 'middle-seat', 'Middle seat', 'The cat peering over the back of an aeroplane seat, cabin full of passengers behind.', 'scene', NULL, 0, 280, 0),
  (29, 'confetti', 'Confetti', 'The cat in a blue party hat with its tongue out, confetti scattered across the floor.', 'scene', NULL, 0, 290, 0),
  (30, 'reading-glasses', 'Reading glasses', 'The cat wearing reading glasses beside an open magazine on a dark table.', 'scene', NULL, 0, 300, 0),
  (31, 'in-a-mug', 'In a mug', 'The cat sitting inside a dark blue mug with one paw over the rim, other mugs behind.', 'scene', NULL, 0, 310, 0),
  (32, 'holding-the-coin', 'Holding the coin', 'The pixel cat in a blue hoodie holding up a glowing gold coin marked with a Z, bright sky behind it.', 'scene', NULL, 0, 320, 0),
  (33, 'the-carnival', 'The carnival', 'The pixel cat holding up one paw in the middle of a crowded meme carnival, with lit booths, sirens and red carpets being pulled off the ground.', 'scene', NULL, 0, 330, 0),
  (34, 'headset', 'Headset', 'The cat wearing a headset at a gaming desk, one paw resting on the mouse mat.', 'scene', NULL, 0, 340, 0),
  (35, 'doing-research', 'Doing research', 'The cat at an old office computer with a paw on the mouse, reading the screen.', 'scene', NULL, 0, 350, 0),
  (36, 'on-the-phone', 'On the phone', 'The cat holding an old flip phone up to its ear against a plain grey background.', 'scene', NULL, 0, 360, 0),
  (37, 'the-necktie', 'The necktie', 'The cat in a necktie at a home office desk, both paws resting on a laptop keyboard.', 'scene', NULL, 0, 370, 0);

INSERT OR IGNORE INTO posts (id, posted_at, body, views, url, pinned) VALUES
  (1, '2026-09-08T00:00:00Z', 'wanted on Zcash

name: $ZECAT
identity: unknown
eyes: redacted
location: shielded
birthplace: shld.fun

crime: becoming the first meme coin on Zcash

the chase has begun. 🐈', '2.9k', 'https://x.com/ZecatZcash/status/2097315787010936926', 1),
  (2, '2026-09-07T00:00:00Z', '@SHLDdotfun has been live on @Zcash for 3 days. here is the complete walkthrough, every step.

funding, trading, slippage, patience.', '7.8k', 'https://x.com/ZecatZcash/status/2096742356544598058', 0),
  (3, '2026-09-18T00:00:00Z', 'everyone is running around, unaware that something big is brewing.', '848', 'https://x.com/ZecatZcash/status/2100948668342030832', 0),
  (4, '2026-09-19T00:00:00Z', 'interesting. all signs point to zec season.', '823', 'https://x.com/ZecatZcash/status/2101168271525601470', 0),
  (5, '2026-09-19T00:00:00Z', '$ZECAT does not want you to become somebody else''s exit liquidity.', '143', 'https://x.com/ZecatZcash/status/2101413934301696033', 0);
